spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:17251/HAPPY_HAPPY
    username: root
    password: test
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      password: password
      port: 16697

swyp:
  jwt:
    secret: 04b0d5112f1afbdc562c552e9ee358619ffd8ed5a9ba41104c6654a2
    access-token-validity-in-milli-seconds: 86400000 # 1일
